using System.Text.Json.Serialization;

namespace WheelDeck.Core.Protocol;

[JsonConverter(typeof(SnakeCaseEnumConverter<ControlId>))]
public enum ControlId
{
    ParkingBrake,
    TurnSignalLeft,
    TurnSignalRight,
    HeadlightToggle,
    LightsOff,
    LightsParking,
    LightsLowbeam,
    HighBeamToggle,
    Wipers,
    CruiseToggle,
    CruiseSetResume,
    EngineStart,
    HazardLights,
    BeaconLights,
    Flasher,
    Horn,
    Trailer,
    LiftDropAxle,
    CameraView,
    GearUp,
    GearDown,
    EngineBrake,
    AirHorn,
    DifferentialLock,
    RetarderIncrease,
    RetarderDecrease,
    QuickInfo,
    MirrorToggle,
    HudWidgets,
    VehicleAdjustment,
    NavigationZoomOut,
    WidgetOptions,
    Services,
    QuickSave,
    QuickLoad,
    Screenshot,
    GarageManager,
    AudioPlayer,
    ShiftToDrive,
    ShiftToReverse,
    ShiftToNeutral,
    EngineElectricity,
    AdaptiveCruise,
    CruiseSpeedIncrease,
    CruiseSpeedDecrease,
    LaneAssistant,
    LaneKeeping,
    EmergencyBrake,
    WipersBack,
    AudioPlayPause,
    AudioNext,
    AudioPrevious,
    AudioVolumeUp,
    AudioVolumeDown,
    AudioFavorite,
    TrailerAxle,

    // Camera pad, numpad mode (ADR-0006: the mode lives in the identifiers).
    CameraPadUp,
    CameraPadDown,
    CameraPadLeft,
    CameraPadRight,
    CameraPadUpLeft,
    CameraPadUpRight,
    CameraPadDownLeft,
    CameraPadDownRight,
    CameraPadRecenter,
    // Camera pad, arrow mode; the four diagonals are disabled and have none.
    CameraPadArrowUp,
    CameraPadArrowDown,
    CameraPadArrowLeft,
    CameraPadArrowRight
}
