package dev.fazrigading.wheeldeck.domain.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/// Snake_case values on the wire, matching protocol/schema/controls.json
/// (ADR-0006: camera pad modes live in the identifiers).
@Serializable
enum class ControlId(val wireValue: String) {
    @SerialName("parking_brake") ParkingBrake("parking_brake"),
    @SerialName("turn_signal_left") TurnSignalLeft("turn_signal_left"),
    @SerialName("turn_signal_right") TurnSignalRight("turn_signal_right"),
    @SerialName("headlight_toggle") HeadlightToggle("headlight_toggle"),
    @SerialName("lights_off") LightsOff("lights_off"),
    @SerialName("lights_parking") LightsParking("lights_parking"),
    @SerialName("lights_lowbeam") LightsLowbeam("lights_lowbeam"),
    @SerialName("high_beam_toggle") HighBeamToggle("high_beam_toggle"),
    @SerialName("wipers") Wipers("wipers"),
    @SerialName("cruise_toggle") CruiseToggle("cruise_toggle"),
    @SerialName("cruise_set_resume") CruiseSetResume("cruise_set_resume"),
    @SerialName("engine_start") EngineStart("engine_start"),
    @SerialName("hazard_lights") HazardLights("hazard_lights"),
    @SerialName("beacon_lights") BeaconLights("beacon_lights"),
    @SerialName("flasher") Flasher("flasher"),
    @SerialName("horn") Horn("horn"),
    @SerialName("trailer") Trailer("trailer"),
    @SerialName("lift_drop_axle") LiftDropAxle("lift_drop_axle"),
    @SerialName("camera_view") CameraView("camera_view"),
    @SerialName("gear_up") GearUp("gear_up"),
    @SerialName("gear_down") GearDown("gear_down"),
    @SerialName("engine_brake") EngineBrake("engine_brake"),
    @SerialName("air_horn") AirHorn("air_horn"),
    @SerialName("differential_lock") DifferentialLock("differential_lock"),
    @SerialName("retarder_increase") RetarderIncrease("retarder_increase"),
    @SerialName("retarder_decrease") RetarderDecrease("retarder_decrease"),
    @SerialName("quick_info") QuickInfo("quick_info"),
    @SerialName("mirror_toggle") MirrorToggle("mirror_toggle"),
    @SerialName("hud_widgets") HudWidgets("hud_widgets"),
    @SerialName("vehicle_adjustment") VehicleAdjustment("vehicle_adjustment"),
    @SerialName("navigation_zoom_out") NavigationZoomOut("navigation_zoom_out"),
    @SerialName("widget_options") WidgetOptions("widget_options"),
    @SerialName("services") Services("services"),
    @SerialName("quick_save") QuickSave("quick_save"),
    @SerialName("quick_load") QuickLoad("quick_load"),
    @SerialName("screenshot") Screenshot("screenshot"),
    @SerialName("garage_manager") GarageManager("garage_manager"),
    @SerialName("audio_player") AudioPlayer("audio_player"),
    @SerialName("shift_to_drive") ShiftToDrive("shift_to_drive"),
    @SerialName("shift_to_reverse") ShiftToReverse("shift_to_reverse"),
    @SerialName("shift_to_neutral") ShiftToNeutral("shift_to_neutral"),
    @SerialName("engine_electricity") EngineElectricity("engine_electricity"),
    @SerialName("adaptive_cruise") AdaptiveCruise("adaptive_cruise"),
    @SerialName("cruise_speed_increase") CruiseSpeedIncrease("cruise_speed_increase"),
    @SerialName("cruise_speed_decrease") CruiseSpeedDecrease("cruise_speed_decrease"),
    @SerialName("lane_assistant") LaneAssistant("lane_assistant"),
    @SerialName("lane_keeping") LaneKeeping("lane_keeping"),
    @SerialName("emergency_brake") EmergencyBrake("emergency_brake"),
    @SerialName("wipers_back") WipersBack("wipers_back"),
    @SerialName("audio_play_pause") AudioPlayPause("audio_play_pause"),
    @SerialName("audio_next") AudioNext("audio_next"),
    @SerialName("audio_previous") AudioPrevious("audio_previous"),
    @SerialName("audio_volume_up") AudioVolumeUp("audio_volume_up"),
    @SerialName("audio_volume_down") AudioVolumeDown("audio_volume_down"),
    @SerialName("audio_favorite") AudioFavorite("audio_favorite"),
    @SerialName("trailer_axle") TrailerAxle("trailer_axle"),
    @SerialName("driver_window_up") DriverWindowUp("driver_window_up"),
    @SerialName("driver_window_down") DriverWindowDown("driver_window_down"),
    @SerialName("passenger_window_up") PassengerWindowUp("passenger_window_up"),
    @SerialName("passenger_window_down") PassengerWindowDown("passenger_window_down"),
    @SerialName("navigation_zoom_in") NavigationZoomIn("navigation_zoom_in"),
    @SerialName("overlay_activation") OverlayActivation("overlay_activation"),
    @SerialName("chat_activation") ChatActivation("chat_activation"),
    @SerialName("quick_replies") QuickReplies("quick_replies"),
    @SerialName("name_tags") NameTags("name_tags"),
    @SerialName("push_to_talk") PushToTalk("push_to_talk"),
    @SerialName("camera_interior") CameraInterior("camera_interior"),
    @SerialName("camera_chasing") CameraChasing("camera_chasing"),
    @SerialName("camera_topdown") CameraTopdown("camera_topdown"),
    @SerialName("camera_roof") CameraRoof("camera_roof"),
    @SerialName("camera_leanout") CameraLeanout("camera_leanout"),
    @SerialName("dashboard_info") DashboardInfo("dashboard_info"),
    @SerialName("next_camera") NextCamera("next_camera"),
    @SerialName("menu") Menu("menu"),
    @SerialName("world_map") WorldMap("world_map"),
    @SerialName("photo_mode") PhotoMode("photo_mode"),
    @SerialName("activate") Activate("activate"),
    // Camera pad, numpad mode (ADR-0006: the mode lives in the identifiers).
    @SerialName("camera_pad_up") CameraPadUp("camera_pad_up"),
    @SerialName("camera_pad_down") CameraPadDown("camera_pad_down"),
    @SerialName("camera_pad_left") CameraPadLeft("camera_pad_left"),
    @SerialName("camera_pad_right") CameraPadRight("camera_pad_right"),
    @SerialName("camera_pad_up_left") CameraPadUpLeft("camera_pad_up_left"),
    @SerialName("camera_pad_up_right") CameraPadUpRight("camera_pad_up_right"),
    @SerialName("camera_pad_down_left") CameraPadDownLeft("camera_pad_down_left"),
    @SerialName("camera_pad_down_right") CameraPadDownRight("camera_pad_down_right"),
    @SerialName("camera_pad_recenter") CameraPadRecenter("camera_pad_recenter"),
    // Camera pad, arrow mode; the four diagonals are disabled and have none.
    @SerialName("camera_pad_arrow_up") CameraPadArrowUp("camera_pad_arrow_up"),
    @SerialName("camera_pad_arrow_down") CameraPadArrowDown("camera_pad_arrow_down"),
    @SerialName("camera_pad_arrow_left") CameraPadArrowLeft("camera_pad_arrow_left"),
    @SerialName("camera_pad_arrow_right") CameraPadArrowRight("camera_pad_arrow_right"),
}

@Serializable
enum class ActionType(val wireValue: String) {
    @SerialName("toggle") Toggle("toggle"),
    @SerialName("press") Press("press"),
    @SerialName("release") Release("release"),
    @SerialName("hold_confirm") HoldConfirm("hold_confirm"),
}
